### PR TITLE
fix typo in prayoga select

### PR DESCRIPTION
**Pull request by vipranarayan14**
Correct "कर्मङि" to "कर्मणि".

### CODE REVIEW

**Comment by akprasad** [comment]
thanks for the fix! the files here are just copied from `ambuda-org/vidyyut` -- could you fix this typo as part of https://github.com/ambuda-org/vidyut/pull/35 ?

**Comment by vipranarayan14** [comment]
oh ok. I see.
Sure, I'll fix it there and add it to #35.

**Comment by vipranarayan14** [comment]
So, I've to fix [this line](https://github.com/ambuda-org/vidyut/blob/998b9c756c83989fd9500c10f7c97bfed4516156/vidyut-prakriya/www/templates/index.html#L109), right?

**Comment by akprasad** [comment]
Yes, exactly

**Pull request closed without merging**
